stages: 
    - slurm

slurmtest:
    stage: slurm
    allow_failure: false
    tags:
    - slurm
    only:
    - runner_cs_access
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - source /opt/conda/etc/profile.d/conda.sh
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - export PYTHONPATH=$CI_PROJECT_DIR
    - srun -p DEV --mem=1000m -c 1 pytest -v test_runner_cs.py
